epoch: 120

LearningRate:
  base_lr: 0.001
  schedulers:
    - name: CosineDecay
      max_epochs: 150
    - name: LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.001
